config/routes.rb
Rails.application.routes.draw do
  
  
  resources :products
  root to: "static_pages#index"

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  
  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50}
    validates :phone, presence: true

    belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

    has_attached_file :avatar, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }#, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }

    has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    include SessionsHelper

    private
        def require_logged_in_user
            unless user_signed_in?
                flash[:danger] = 'Área restrita. Por favor, realize login para acessar.'
                redirect_to entrar_path
            end
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto Cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category, :avatar)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to contacts_path
    else
      flash.now[:danger] = 'Email ou senha inválidos'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logout com sucesso'
    redirect_to entrar_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
        @name = "Souza Junior"
    end

    def contato
        
    end

    def sobre

    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in_user, only:[:edit, :update]

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save 
            flash[:success] = "Usuário cadastrado com sucesso!"
            redirect_to entrar_url
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if current_user.update(user_params)
            flash[:success] = 'Dados atualizados com sucesso'
            redirect_to contacts_url
        else
            render "edit"
        end
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end

    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control', placeholder: "Seu Celular", :onkeypress =>'if (!isNaN(String.fromCharCode(window.event.keyCode))) return true; else return false;', minimum: '11', maximum: '11', size: '11', required:"required" %>
</div>

app/views/contacts/edit.html.erb
<div class="row data-forms">
    <div class="col-md-6 col-xs-12">
        <h1>Editar Contato</h1>
    </div>

    <div class="col-md-6 col-xs-12">
        <%= form_for @contact do |f| %>
            <%= render 'form', f: f %>
            <%= f.submit 'Atualizar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/contacts/index.html.erb
<div class="row table-contacts">
  <div class="col-xs-12 text-center">
    <h1>Meus Contatos</h1>
  </div>

  <div class="col-md-8 colmd-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Telefone</th>
          <th colspan="2">
            Ações
            <%= link_to 'Novo Contato', new_contact_path, class: 'btn btn-success'  %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @contacts.empty? %>
          <tr>
            <td colspan="4" class="text-center">
              <h3>Não existem contatos cadastrados.</h3>
              <%= link_to 'Clique Aqui', new_contact_path %> para cadastrar um novo contato
            </td>
          </tr>
        <% end %>
        <% @contacts.each do |c| %>
          <tr>
            <td>
              <%= c.name %>
            </td>
            <td>
              <%= c.phone %>
            </td>
            <td>
              <%= link_to 'Editar', edit_contact_path(c), class: 'btn btn-warning' %>
            </td>
            <td>
              <%= link_to 'Excluir', contact_path(c), method: :delete, class: 'btn btn-danger', data: { confirm: 'Tem certeza que deseja excluir contato?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row data-forms">
    <div class="col-md-6 col-xs-12">
        <h1>Adicionar Novo Contato</h1>
    </div>

    <div class="col-md-6 col-xs-12">
        <%= form_for @contact do |f| %>
            <%= render 'form', f: f %>
            <%= f.submit 'Salvar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class="alert alert-danger">
            Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros')%>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Store Stickers. Todos os direitos reservados', root_path %>
    </small>
    
    <nav class="nav-footer">
        <ul class="list-sub">
            <li>
                <%= link_to 'Sobre Nós', sobre_path %>
            </li>
            <li>
                <%= link_to 'Contato', contato_path %>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top nav-menus">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= image_tag("online-learning.svg", class:"icon-logo")%>
            <%= link_to 'Store Stickers', root_url, class:'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="expanded-menu">
            <ul class="nav navbar-nav">
            <% if !user_signed_in? %>
                <li class="active">
                    <%= link_to 'Nova Conta', new_user_path, class:'btn-new' %>
                </li>
            <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if !user_signed_in? %>
                    <li>
                        <%= link_to 'Entrar', entrar_path %>
                    </li>
                <% elsif user_signed_in? %>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Bem vindo, <%= current_user.name %> <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li>
                                <%= link_to 'Meus Contatos', contacts_path, class:'dropdown-item' %>
                            </li>
                            <li>
                                <%= link_to 'Meus Produtos', products_path, class:'dropdown-item' %>
                            </li>
                            <li>
                                <%= link_to 'Editar', edit_user_path(current_user) , class:'dropdown-item' %>
                            </li>
                            <li class="divider" role="separator"></li>
                            <li>
                                <%= link_to 'Sair', sair_path , method: :delete , class:'dropdown-item'%>
                            </li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store Stickers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('guarantee.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
    
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: 'alert alert-#{message_type} alert-dismissible', role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product, local: true, html: { multipart: true } do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Categoria %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :Anexar_Imagem %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Visualizar', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row header-page">
  <div class="col-md-6 col-xs-6 title-page">
    <h1>Produtos</h1>
  </div>
  
  <div class="col-md-6 col-xs-6 button-page">
    <%= link_to 'Novo Produto', new_product_path, class: 'btn btn-success' %>
  </div>
</div>
<div class="row content-cards">
  <% @products.each do |product| %>
    <div class="col-md-3 col-xs-3 col-card">
      <div class="row">
        <div class="card">
          <%= image_tag product.avatar.url(:large) %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text"><i>categoria: <%= product.category %></i></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="dropdown">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opções <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><%= link_to 'Exibir', product %></li>
            <li><%= link_to 'Editar', edit_product_path(product), class: 'btn-warning' %></li>
            <li><%= link_to 'Excluir', product, method: :delete, class: 'btn-danger', data: { confirm: 'Tem certeza que deseja excluir contato?' } %></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!--
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @products.each do |product| %>
      <tr>
        <td><%#= product.name %></td>
        <td><%#= product.category %></td>
        <td><%#= link_to 'Show', product %></td>
        <td><%#= link_to 'Edit', edit_product_path(product) %></td>
        <td><%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'Novo Produto', new_product_path, class: 'btn btn-success' %>
-->

app/views/products/new.html.erb
<h1>Cadastrar Novo Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @product.name %>
</p>

<p>
  <b>Categoria:</b>
  <%= @product.category %>
</p>

<p>
  <%= image_tag @product.avatar.url(:large) %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
    Entre em contato com <a href="https://www.linkedin.com/in/juniorsouz4/">Souz4 Junior</a> para saber mais.
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
    
    <%= image_tag("guarantee.svg", class:"icon-logo", style:'width: 60px;')%>
    <h1><b>Store Stickers<b></h1>
    <p>
        Somos especialistas em adesivos que personalizam sua vida!
    </p>
    <p>
        <%= link_to 'Crie Sua Conta', new_user_path , class:'btn btn-primary btn-lg' %>
    </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>
<p>
    Somos uma industria especializada na produção de adesivos. Qualidade, variedade e inovação são os critérios utilizados por nossa equipe.
</p>
<p>
    Buscamos os melhores fornecedores de matéria-prima e os melhores e mais atualizados artistas para que o nosso público encontre a variedade, a seleção e a qualidade que procura. Tudo em único lugar.
</p>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
</div>

<div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
</div>

<div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>
</div>

<div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="row data-forms">
    <div class="col-md-6 col-xs-12">
        <h1>Editar Dados</h1>
    </div>
    <div class="col-md-6 col-xs-12">
        <%= form_for current_user do |f| %>

            <%= render 'form', f: f %>

            <%= f.submit 'Salvar', class: 'btn btn-primary'%>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row data-forms">
    <div class="col-md-6 col-xs-12">
        <h1>Cadastre-se</h1>
    </div>
    <div class="col-md-6 col-xs-12">
        <%= form_for @user do |f| %>

            <%= render 'form', f: f %>

            <%= f.submit 'Cadastrar', class: 'btn btn-primary'%>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h2>Olá <%= current_user.name %></h2>